name=PrintfSerial
version=1.0.0
author=Ilmirrizki
maintainer=Ilmirrizki
sentence=Library printf untuk USART Serial AVR/Arduino.
paragraph=Mengintegrasikan stdout ke Hardware USART agar printf bawaan C dapat digunakan langsung di Arduino/Wokwi.
category=Communication
url=https://github.com/ilmirrizki/printf-serial-avr
architectures=*
